### ISSUE TITLE
Problem  after installation

### ISSUE THREAD

**Issue by wojtas911** [leonardfischer/faktura#22]
Hi,
I have a problem after installation,
After install wizard, system redirect to /user all the time, but /user - 404 not found.
I have no idea what else I can do.
I've trayed to install all frameworks, but with out luck.

**Comment by solidsnake** [comment]
Hi, 
have you checked your .htaccess and the "base_url" setting in application/bootstrap.php? Does your apache configuration allow URL rewriting?
